---
abstract: 'Output progress to terminal as simple message'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Progress-Any-Output-TermMessage
requires:
  Progress::Any: 0.10
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Progress-Any-Output-TermMessage
  repository: http://github.com/sharyanto/perl-Progress-Any-Output-TermMessage
version: 0.02
